[project]
name = "veo3-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.21.0",
    "aiohttp>=3.12.15",
    "boto3>=1.40.4",
    "fastapi[standard]>=0.116.1",
    "pydantic-settings>=2.10.1",
]
