"""empty message

Revision ID: 112884a08de7
Revises: 
Create Date: 2025-10-05 22:35:20.090013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112884a08de7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'PARTNER', 'ADMIN', name='userrole'), server_default=sa.text("'USER'"), nullable=False),
    sa.Column('referrer_type', sa.Enum('USER', 'PARTNER', name='referrertype'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'PARTNER', 'ADMIN', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('users')
    # ### end Alembic commands ###
