"""empty message

Revision ID: 5bbc7e80b4f0
Revises: 18b11caad14b
Create Date: 2025-10-04 13:27:29.928061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbc7e80b4f0'
down_revision: Union[str, Sequence[str], None] = '18b11caad14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_links', sa.Column('user_chat_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref_links', 'user_chat_id')
    # ### end Alembic commands ###
