"""empty message

Revision ID: 5eb07c1c96ed
Revises: 18c502ea2eac
Create Date: 2025-10-05 22:43:26.236188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb07c1c96ed'
down_revision: Union[str, Sequence[str], None] = '18c502ea2eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer_type', sa.Enum('USER', 'PARTNER', name='referrertype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referrer_type')
    # ### end Alembic commands ###
